In [1]:
from array import*
arr=array('i',[1,2,3,4,5])
arr[4]

5

In [2]:
arr[1:4]

array('i', [2, 3, 4])

In [3]:
arr.append(5)

In [4]:
arr

array('i', [1, 2, 3, 4, 5, 5])

In [5]:
arr.append(7)

In [6]:
arr

array('i', [1, 2, 3, 4, 5, 5, 7])

In [7]:
arr.insert(0,8)

In [8]:
arr

array('i', [8, 1, 2, 3, 4, 5, 5, 7])

In [9]:
sorted(arr)

[1, 2, 3, 4, 5, 5, 7, 8]

In [10]:
arr.tolist()

[8, 1, 2, 3, 4, 5, 5, 7]

In [11]:
x=arr.pop(0)

In [12]:
x

8

In [13]:
arr.remove(3)

In [14]:
arr

array('i', [1, 2, 4, 5, 5, 7])

In [15]:
arr.remove(7)

In [16]:
arr

array('i', [1, 2, 4, 5, 5])

In [17]:
arr2=array('i',[6,7,8,9,0])
arr.extend(arr2)

In [18]:
arr

array('i', [1, 2, 4, 5, 5, 6, 7, 8, 9, 0])

In [19]:
arr.reverse()

In [20]:
arr

array('i', [0, 9, 8, 7, 6, 5, 5, 4, 2, 1])

In [21]:
arr.index(2)

8

In [23]:
from array import*
arr=array('i',[])
tol=int(0)
for i in range(0,5):
    x=int(input("enter the marks "))
    arr.append(x)
    tol=tol+x

print(tol/5)


enter the marks 1223
enter the marks 1231
enter the marks 133
enter the marks 131
enter the marks 13
546.2


In [37]:
from array import*
arr=array('i',[1,3,4,5,6,0])
x=int(input("enter the number : "))
for i in range(0,len(arr)):
    if arr[i]==x:
        print(i)
        break

enter the number : 5
3


In [43]:
from array import*
tol=int(0)
arr=array('i',[])
arr1=array('i',[89,67,89,78,80])
arr2=array('i',[89,67,89,78,80])
arr3=array('i',[89,67,89,78,80])
arr4=array('i',[89,67,89,78,80])
arr5=array('i',[89,67,89,78,80])
arr6=array('i',[89,67,89,78,80])
for i in range(0,len(arr1)):
    x=arr1[i]+arr2[i]+arr3[i]+arr4[i]+arr5[i]+arr6[i]
    arr.append(x)
    tol=tol+x
    
print(tol/30)
    



80.6


In [91]:
from array import*
arr=array('i',[])
f2=float()
x=float(input("enter the starting point : "))
y=float(input("enter the ending point :"))
z=int(input("enter the no of numbers :"))
d=(y-x)/z+1
a=0
for i in range(0,z):
    a=a+(i+1)*d
    print(a)

enter the starting point : 0
enter the ending point :10
enter the no of numbers :10
2.0
6.0
12.0
20.0
30.0
42.0
56.0
72.0
90.0
110.0


In [49]:
from numpy import*
arr7=array([[1,2,3],[2,6,7]])

In [50]:
arr7

array([[1, 2, 3],
       [2, 6, 7]])

In [53]:
arr=linspace(1,10,20)

In [54]:
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [55]:
arr=zeros(5)

In [56]:
arr

array([0., 0., 0., 0., 0.])

In [57]:
arr=ones(10)

In [58]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
arr.a

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [94]:
from numpy import*
arr=array([1,2,3,4])

In [95]:
arr


array([1, 2, 3, 4])

In [98]:
sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [99]:
min(arr)

1

In [100]:
max(arr)

4

In [101]:
sum(arr)

10

In [102]:
sort(arr)

array([1, 2, 3, 4])

In [103]:
var(arr)

1.25

In [104]:
cov(arr)

array(1.66666667)

In [105]:
std(arr)

1.118033988749895

In [106]:
mean(arr)

2.5

In [108]:
median(arr)

2.5

In [109]:
append(arr,(7))

array([1, 2, 3, 4, 7])

In [113]:
delete(arr,(3))

array([1, 2, 3])

In [116]:
from numpy import*
arr=zeros(5)
arr1=ones(5)
arr2=array([4,5,6,7,8])
arr4=array([])
for i in range(0,5):
    arr4=append(arr4,(arr[i]))
    arr4=append(arr4,(arr1[i]))
    arr4=append(arr4,(arr2[i]))
print(arr4)
    
    

[0. 1. 4. 0. 1. 5. 0. 1. 6. 0. 1. 7. 0. 1. 8.]


In [120]:
from numpy import*
arr=array([[],[]])
arr1=array([[1,2,3],[2,6,7]])
arr2=array([[4,5,6],[4,5,6]])
for i in range(0,2):
    for j in range(0,3):
        a=arr1[i][j]+arr2[i][j]
        arr=append(arr,(a))
        
print(arr)

[ 5.  7.  9.  6. 11. 13.]


In [123]:
from numpy import*
arr=array([[1,2,3],[4,5,6]])
arr1=array([])
for i in range(0,2):
    for j in range(0,3):
        a=arr[i][j]
        arr1=append(arr1,(a))
        
print(arr1)
        

[1. 2. 3. 4. 5. 6.]


In [124]:
from numpy import*
arr=array([[1,2,3],[6,7,8]])
if any(arr>=6):
    print("found")

found


In [125]:
if all(a>0):
    print("found")

found
